### ISSUE TITLE
Feedback for "Supported SAP HANA Web-based Tools"

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-neo-environment#2]
https://help.sap.com/docs/BTP/ea72206b834e4ace9cd834feed6c0e09/ad3717d2c242436095fd12c158d7876f.html?locale=en-US&q=neo

The link for HANA Cockpit https://<database instance><subaccount>.<host>/sap/hana/xs/admin/cockpit does not work for our HANA on Neo.

The HANA XSC Cockpit was discontinued with HANA 2.0 and that Cockpit had URLs like https://<database instance><subaccount>.<host>/sap/hana/admin/cockpit - whithout xs.

For HANA 2.0 the HANA Cockpit is a separate installation On-Premise - I don't know what the current state for HANAs on Neo is.

Kind regards,
Sebastian

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Madeline-Schaefer** [comment]
Thank you for feedback. I will have a look at this and get back to you with information or an update as soon as possible.

Kind regards,
Madeline

**Comment by Madeline-Schaefer** [comment]
@sebastianesch Thanks again for your feedback. The documentation will be updated on SAP Help Protal with the next release.

**Comment by sebastianesch** [comment]
https://people.sap.com/sebastian.esch
