### ISSUE TITLE
Incorrect link provided in the documentation

### ISSUE THREAD

**Issue by Santaneel** [SAP-docs/btp-neo-environment#5]
### Issue description

The link for Audit and Logging Information for SAP Cloud Integration (Neo) leads to Cloud Foundry documentation. 
Please check and update.

![image](https://github.com/SAP-docs/btp-neo-environment/assets/17881202/db1c38a4-34eb-4910-9e98-97228df4aa12)

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Security Events Logged by the Neo Services

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-btp-neo-environment/security-events-logged-by-neo-services

**Comment by nikolasimeonov77** [comment]
Hi @Santaneel,
It looks like the link is fixed now. Let me know if there are other issues by reopneing this GitHub item.
